#!/usr/bin/env zsh

BASEDIR="$(cd "$(dirname "${ZSH_SOURCE[0]}")" && pwd)"

link_dev() {
  ln -sfn ${BASEDIR}/vim/vim $HOME/.vim
  ln -sfn ${BASEDIR}/vim/vimrc $HOME/.vimrc
  ln -sfn ${BASEDIR}/vim/gvimrc $HOME/.gvimrc

  ln -sfn ${BASEDIR}/zsh/zsh $HOME/.zsh
  ln -sfn ${BASEDIR}/zsh/zprofile $HOME/.zprofile
  ln -sfn ${BASEDIR}/zsh/zshenv $HOME/.zshenv
  ln -sfn ${BASEDIR}/zsh/zshrc $HOME/.zshrc

  ln -sfn ${BASEDIR}/tmux/tmux.conf $HOME/.tmux.conf
  ln -sfn ${BASEDIR}/git/gitconfig $HOME/.gitconfig
  ln -sfn ${BASEDIR}/git/gitignore $HOME/.gitignore
  ln -sfn ${BASEDIR}/git/gitattributes $HOME/.gitattributes
  ln -sfn ${BASEDIR}/ruby/irbrc $HOME/.irbrc
  ln -sfn ${BASEDIR}/scheme/csirc $HOME/.csirc
  ln -sfn ${BASEDIR}/rg/rgignore $HOME/.rgignore
  ln -sfn ${BASEDIR}/ctags/ctags $HOME/.ctags

  [ -d $HOME/.config/alacritty/ ] || mkdir -p $HOME/.config/alacritty
  ln -sfn ${BASEDIR}/alacritty/alacritty.yml $HOME/.config/alacritty/alacritty.yml
  ln -sfn ${BASEDIR}/alacritty/colors.yml $HOME/.config/alacritty/colors.yml

  echo "Installing Vim plugins..."
  vim -E -c PlugInstall  -c qall
  vim -c 'CocInstall -sync coc-go coc-tsserver coc-html coc-css coc-emmet coc-solargraph|q'

  echo "Source Zsh files"
  source $HOME/.zshrc
}

link_linux() {
  ln -sfn ${BASEDIR}/bin/fehbg $HOME/.fehbg

  ln -sfn ${BASEDIR}/X11/xinitrc $HOME/.xinitrc
  ln -sfn ${BASEDIR}/X11/Xresources $HOME/.Xresources

  [ -d $HOME/.config/rofi/ ] || mkdir -p $HOME/.config/rofi
  ln -sfn ${BASEDIR}/rofi/config $HOME/.config/rofi/config

  [ -d $HOME/.config/dunst/ ] || mkdir -p $HOME/.config/dunst
  ln -sfn ${BASEDIR}/dunst/dunstrc $HOME/.config/dunst/dunstrc

  [ -d $HOME/.config/picom/ ] || mkdir -p $HOME/.config/picom
  ln -sfn ${BASEDIR}/picom/picom.conf $HOME/.config/picom/picom.conf

  ln -sfn ${BASEDIR}/fontconfig $HOME/.config/fontconfig

  [ -d $HOME/.config/zathura/ ] || mkdir -p $HOME/.config/zathura
  ln -sfn ${BASEDIR}/zathura/zathurarc $HOME/.config/zathura/zathurarc
}

link_macos() {}

link_cli_tools() {
  ln -sfn ${BASEDIR}/nnn/plugins $HOME/.config/nnn/plugins

  [ -d $HOME/.newsboat/ ] || mkdir -p $HOME/.newsboat
  ln -sfn ${BASEDIR}/newsboat/config $HOME/.newsboat/config
  ln -sfn ${BASEDIR}/newsboat/urls $HOME/.newsboat/urls

  [ -d $HOME/.config/cmus/ ] || mkdir -p $HOME/.config/cmus
  ln -sfn ${BASEDIR}/cmus/aaku.theme $HOME/.config/cmus/aaku.theme
  ln -sfn ${BASEDIR}/cmus/rc $HOME/.config/cmus/rc

  [ -d $HOME/.irssi ] || mkdir -p $HOME/.irssi
  ln -sfn ${BASEDIR}/irssi/config $HOME/.irssi/config
  ln -sfn ${BASEDIR}/irssi/weed.theme $HOME/.irssi/weed.theme
  ln -sfn ${BASEDIR}/irssi/scripts $HOME/.irssi/scripts
}

link_fonts() {
  echo "Installing Fonts..."
  [ -d $HOME/Workspace/fonts/ ] && exit
  git clone https://github.com/powerline/fonts.git $HOME/Workspace/fonts/
  pushd $HOME/Workspace/fonts && ./install.sh && popd

  git clone https://github.com/sebastiencs/icons-in-terminal.git $HOME/Workspace/fonts/icons-in-terminal
  pushd $HOME/Workspace/fonts/icons-in-terminal && ./install.sh && popd
}

echo "Creating Workspace..."
# mkdir $HOME/Workspace

echo "Updating submodules..."
# git submodule update --init --recursive --remote

if [ $# -eq 0 ]; then
  echo "Installing all..."
  link_dev
  link_linux
  link_macos
  link_cli_tools
  link_fonts
elif [[ condition ]]; then
  while test $# -gt 0
  do
    case "$1" in
      dev)
        echo "Installing dev..."
        link_dev
        ;;
      linux)
        echo "Installing linux..."
        link_linux
        ;;
      macos)
        echo "Installing macos..."
        link_macos
        ;;
      cli)
        echo "Installing cli..."
        link_cli_tools
        ;;
      fonts)
        echo "Installing fonts..."
        link_fonts
        ;;
      *)
        echo "Usage: $0 [*|dev|linux|macos|cli|fonts]"
        ;;
    esac
    shift
  done
fi
