#!/usr/bin/env zsh

BASEDIR="$(cd "$(dirname "${ZSH_SOURCE[0]}")" && pwd)"

echo "Updating submodules..."
git submodule update --init --recursive --remote

echo "Linking files..."
ln -sfn ${BASEDIR}/vim/vim/ ~/.vim
ln -sfn ${BASEDIR}/vim/vimrc ~/.vimrc
ln -sfn ${BASEDIR}/vim/gvimrc ~/.gvimrc

ln -sfn ${BASEDIR}/zsh/zsh/ ~/.zsh
ln -sfn ${BASEDIR}/zsh/zprofile ~/.zprofile
ln -sfn ${BASEDIR}/zsh/zshenv ~/.zshenv
ln -sfn ${BASEDIR}/zsh/zshrc ~/.zshrc

ln -sfn ${BASEDIR}/tmux/tmux.conf ~/.tmux.conf
ln -sfn ${BASEDIR}/git/gitconfig ~/.gitconfig

ln -sfn ${BASEDIR}/other/agignore ~/.agignore
ln -sfn ${BASEDIR}/other/Xresources ~/.Xresources

[ -d $HOME/.config/termite/ ] || mkdir -p $HOME/.config/termite
ln -sfrn ${BASEDIR}/other/termite ~/.config/termite/config

echo "Installing Vim plugins ..."
echo | vim +PlugInstall +qall

echo "Source Zsh files"
source ~/.zshrc

echo "Installing Fonts..."
git clone https://github.com/powerline/fonts.git ~/workspace/fonts/ && ~/workspace/fonts/install.sh
