#!/usr/bin/env bash

# Ubuntu based systems
echo "Installing required packages"
sudo apt-get install -y \
  zsh \
  vim \
  tmux \
  git \
  curl \
  silversearcher-ag \
  xsel \
  cmus \
  weechat

echo "Changing default shell to Zsh"
chsh -s $(which zsh)

echo "Installing Rbenv"
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
