#!/usr/bin/env sh

# load scriptting adittion
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
# focus window that your mouse hovers on (disabled due to right click bugs)
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
# floating windows always stay on top
yabai -m config window_topmost               on
# enable borders
yabai -m config window_border                off
# no clue what this is
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
# don't automatically rebalance windows
yabai -m config auto_balance                 off
# swap windows if moved with mouse
yabai -m config mouse_action1                move
# resize windows if resized with mouse
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   15

# SIP Required
# prevent border from being under the active window
yabai -m config active_window_border_topmost on
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xffff3050
yabai -m config normal_window_border_color   0xffaaaaaa

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="Preferences$" manage=off topmost=on
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="Calendar" manage=off
yabai -m rule --add app="Spotify" manage=off
yabai -m rule --add app="Anghami" manage=off
yabai -m rule --add app="Slack" manage=off
yabai -m rule --add app="zoom.us" manage=off
yabai -m rule --add app="^.*VPN.*$" manage=off
yabai -m rule --add app="KeeWeb" manage=off
yabai -m rule --add app="^.*Docker.*$" manage=off
yabai -m rule --add app="^.*VLC.*$" manage=off
