#!/usr/bin/env zsh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
export QT_AUTO_SCREEN_SCALE_FACTOR=0

xrdb ~/.Xresources &
xsetroot -cursor_name left_ptr &
xrandr --output eDP-1 --mode 1920x1080 --dpi 96 &
dunst -config $HOME/.config/dunst/dunstrc &
$HOME/.fehbg &
compton --config $HOME/.config/compton/compton.conf -b
nm-applet 2>&1 /dev/null &
udiskie &
dropbox &
onpar  &

exec dwm
