export WEATHER_API_KEY='aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
export WEATHER_CITY_GEOLOCATION='44.44444,55.555555'
export PRAYER_API_PARAMS='city=Jerusalem&country=PS&method=3'

export AWS_ACCESS_KEY_ID='VVVVVVVVVVVVVVVVVVVV'
export AWS_SECRET_ACCESS_KEY='WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW'
export AWS_REGION='us-east-2'

export NIN_INTEGRATION_CLIENT='todoist'
export NIN_INTEGRATION_CLIENT_TOKEN='VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV'
export COD_TODOIST_TOKEN='VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV'
