set guifont=Hack\ Regular\ 10

" Window size
set lines=50
set columns=90
set guiheadroom=0

" Menus
set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar

" Remove balloon
set noballooneval
let g:netrw_nobeval = 1

" show console dialogs
set guioptions+=c

" Silent bell
autocmd GUIEnter * set vb t_vb=

highlight Normal       guibg=#1b1918
highlight StatusLine   guifg=Grey15 guibg=Grey35
highlight StatusLineNC guifg=Grey15 guibg=Grey23
