#!/usr/bin/env zsh

parse_battery_details () {
  local battery_device=0
  local response=$(acpi -b | grep "Battery ${battery_device}")

  state=$(echo "${response}" | grep -wo "Full\|Charging\|Discharging")
  power=$(echo "${response}" | grep -o '[0-9]\+%' | tr -d '%')
}

print_battery () {
  local critical_level=10

  if [[ "${state}" = "Full" ]]; then
    battery="  ${power}%"
    color="#5ab738"
  elif [[ "${state}" = "Charging" ]]; then
    battery=" ${power}%"
  elif [[ "${state}" = "Discharging" ]]; then
    if [[ "${power}" -le "${critical_level}" ]]; then
      battery="  ${power}%"
      color="#f22c40"
    elif [[ "${power}" -le "50" ]]; then
      battery="  ${power}%"
    else
      battery="  ${power}%"
    fi
  fi

  echo "${battery}"
  echo "${battery}"
  echo "$color"
}

print_battery

exit 0
