#!/usr/bin/env zsh

# Use the provided interface, otherwise the device used for the default route.
if [[ -n $BLOCK_INSTANCE ]]; then
  interface=$BLOCK_INSTANCE
else
  interface=$(ip route | awk '/^default/ { print $5 ; exit }')
fi

[[ ! -d /sys/class/net/${interface} ]] && exit

if [[ "$(cat /sys/class/net/$interface/operstate)" = 'up' ]]; then
  iface=""
  color="#ffffff"
else
  iface=""
  color="#f22c40"
fi

echo "${iface}"
echo "${iface}"
echo "$color"

exit 0
