#!/usr/bin/env zsh

parse_prayer_times () {
  local api_parameters="city=Cairo&country=EG&method=2"
  local api_url="http://api.aladhan.com/timingsByCity?${api_parameters}"
  local response=$(curl -s "${api_url}")

  local prayers=('Fajr' 'Sunrise' 'Dhuhr' 'Asr' 'Maghrib' 'Isha')
  for prayer in "${prayers[@]}"; do
    local prayer_parsed_time=$(echo "${response}" \
      | grep -o -e "\"${prayer}\":\"[0-9][0-9]:[0-9][0-9]\"" \
      | awk -F "\"${prayer}\":" '{print $2}' | tr -d '"')

    local prayer_time_in_seconds=$(date -d "${prayer_parsed_time}" +"%s")
    local seconds_until_prayer=$(($prayer_time_in_seconds - $(date +'%s')))
    if [[ $seconds_until_prayer > 0 ]]; then
      (( $seconds_until_prayer < min || min == 0 )) \
        && min=$seconds_until_prayer \
        && prayer_name=$prayer \
        && prayer_time=$prayer_parsed_time \
        && seconds_left=$min
    fi
  done
}

print_prayer () {
  parse_prayer_times

  report_mode=${BLOCK_INSTANCE:=0}
  if [[ $report_mode == 1 ]]; then
    minutes_left=$(($seconds_left / 60))
    prayer="${prayer_name} ${minutes_left} Minutes Left"
  else
    prayer="${prayer_name} ${prayer_time}"
  fi

  echo "${prayer}"
  echo "${prayer}"
  echo "#5ab738"
}

print_prayer
exit 0
