#!/usr/bin/env bash

current_part_of_the_day() {
  local current_hour=$(date +"%H")
  local day='5'
  local night='17'

  if [ ${current_hour} -ge ${day} -a ${current_hour} -le ${night} ]; then
    echo "day"
  else
    echo "night"
  fi
}

parse_weather_details () {
  local api_key="cabfc935d0f32912c7fc1f963648b2fd"
  local api_parameters="exclude=minutely,hourly,daily,alerts,flags&units=si"
  local city_id="29.98333,31.445127"
  local api_url="https://api.darksky.net/forecast/${api_key}/${city_id}?${api_parameters}"

  local response=$(curl -s "${api_url}")
  status=$(echo "${response}" | grep -o -e '\"summary\":\"[a-zA-Z ]*\"' | awk -F ':' '{print $2}' | tr -d '"')
  temperature=$(echo "${response}" | grep -o -e '\"temperature\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
}

print_weather () {
  local sun_icon=""
  local night_icon=""
  local cloud_icon=""
  local rain_icon=""
  local storm_icon=""
  local snow_icon=""
  local fog_icon=""
  local celsius_symbol="°C" 

  parse_weather_details

  if [[ "${status}" = *Snow* ]]; then
    weather="${snow_icon}  ${temperature}${celsius_symbol}"
  elif [[ "${status}" = *Rain* ]] || [[ "${status}" = *Drizzle* ]]; then
    weather="${rain_icon}  ${temperature}${celsius_symbol}"
  elif [[ "${status}" = *Cloud* ]] || [[ "${status}" = *Overcast* ]]; then
    weather="${cloud_icon}  ${temperature}${celsius_symbol}"
  elif [[ "${status}" = *Clear* ]]; then
    local current_time="$(current_part_of_the_day)"
    if [[ "$current_time" == "day" ]]; then
      weather="${sun_icon}  ${temperature}${celsius_symbol}"
    else
      weather="${night_icon}  ${temperature}${celsius_symbol}"
    fi
  elif [[ "${status}" = *Fog* ]] || [[ "${status}" = *Mist* ]] || [[ "${status}" = *Haze* ]]; then
    weather="${fog_icon}  ${temperature}${celsius_symbol}"
  else
    weather="${status}  ${temperature}${celsius_symbol}"
  fi

  echo "${weather}"
  echo "${weather}"
}

print_weather

exit 0
