#!/usr/bin/env zsh

parse_weather_details () {
  local api_key="cabfc935d0f32912c7fc1f963648b2fd"
  local api_parameters="exclude=minutely,hourly,daily,alerts,flags&units=si"
  local city_id="29.98333,31.445127"
  local api_url="https://api.darksky.net/forecast/${api_key}/${city_id}?${api_parameters}"

  local response=$(curl -s "${api_url}")
  [[ -z $response ]] && exit 0

  forecast=$(echo "${response}" | grep -o -e '\"icon\":\"[a-zA-Z-]*\"' | awk -F ':' '{print $2}' | tr -d '"')
  temperature=$(echo "${response}" | grep -o -e '\"temperature\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
}

print_weather () {
  local sun_icon=""
  local night_icon=""
  local cloud_icon=""
  local rain_icon=""
  local snow_icon=""
  local wind_icon=""
  local storm_icon=""
  local fog_icon=""
  local celsius_symbol="°C"

  parse_weather_details

  if [[ "${forecast}" = *clear-day* ]]; then
      weather="${sun_icon}  ${temperature}${celsius_symbol}"
  elif [[ "${forecast}" = *clear-night* ]]; then
      weather="${night_icon}  ${temperature}${celsius_symbol}"
  elif [[ "${forecast}" = *cloudy* ]]; then
    weather="${cloud_icon}  ${temperature}${celsius_symbol}"
  elif [[ "${forecast}" = *rain* ]]; then
    weather="${rain_icon}  ${temperature}${celsius_symbol}"
  elif [[ "${forecast}" = *snow* ]] || [[ "${forecast}" = *sleet* ]]; then
    weather="${snow_icon}  ${temperature}${celsius_symbol}"
  elif [[ "${forecast}" = *wind* ]]; then
    weather="${wind_icon}  ${temperature}${celsius_symbol}"
  elif [[ "${forecast}" = *fog* ]]; then
    weather="${fog_icon}  ${temperature}${celsius_symbol}"
  else
    weather="${forecast}  ${temperature}${celsius_symbol}"
  fi

  echo "${weather}"
  echo "${weather}"
}

print_weather

exit 0
