#!/usr/bin/env zsh

# Use the provided interface, otherwise the device used for the default route.
if [[ -n $ETHERNET_INTERFACE ]]; then
  interface=$ETHERNET_INTERFACE
else
  interface=$(ip route | awk '/^default/ { print $5 ; exit }')
fi

[[ ! -d /sys/class/net/${interface} ]] && exit

if [[ "$(cat /sys/class/net/$interface/operstate)" = 'up' ]]; then
  iface=""
  msg_color="#ffffff"
else
  iface=""
  msg_color="#f22c40"
fi

echo "${iface}"
echo "${iface}"
echo "$msg_color"

exit 0
