#!/usr/bin/env zsh

language=$(setxkbmap -query | awk '/layout/{print $2}')

case "$language" in
  'ara')
    layout='ar' ;;
  'us'|*)
    layout='en' ;;
esac

echo "  $layout"
echo "  $layout"

exit 0
