#!/usr/bin/env zsh

interface="${WIFI_INTERFACE:-wlan0}"

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${interface}/wireless ]] ||
    [[ "$(cat /sys/class/net/$interface/operstate)" = 'down' ]] && exit

strength=$(grep $interface /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

echo "  $strength%"
echo "  $strength%"

exit 0
