# sourced always

# in case a non-interactive shell is not running
if [[ $- != *i* ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc"
fi

export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'
export MANPAGER='less -s -M +Gg'
export TERMINAL='alacritty'
export BROWSER='firefox'
export TERM='xterm-256color'
