# sourced in interactive shell

include () {
  [[ -f "$1" ]] && source "$1" "${@: 2}"
}

zprof() {
  time zsh -i -c exit
}

export WK="$HOME/workspace"

if [ -d $HOME/.zsh ]; then
  for file in $HOME/.zsh/**/*.zsh; do
    source $file
  done
fi

export AAKU="$WK/aaku"
export PATH="$PATH:$AAKU/bin"
export PATH="$PATH:$WK/bin"
export PATH="$PATH:$WK/onpar/bin"
export PATH="$PATH:$HOME/.cargo/bin"

# FZF
export FZF_DEFAULT_COMMAND='rg --files --hidden --color never'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# K8S
kubectl() {
  unset -f kubectl
  source <(kubectl completion zsh 2>/dev/null)
  kubectl $@
}

# Homebrew
if command -v /opt/homebrew/bin/brew &> /dev/null; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Mise
if command -v $HOME/.local/bin/mise &> /dev/null; then
  eval "$($HOME/.local/bin/mise activate zsh)"
fi

# Rust
include $HOME/.cargo/env

# Ruby
include /usr/share/chruby/chruby.sh
include /usr/share/chruby/auto.sh
include $HOMEBREW_PREFIX/opt/chruby/share/chruby/chruby.sh
include $HOMEBREW_PREFIX/opt/chruby/share/chruby/auto.sh
export PATH="$HOMEBREW_PREFIX/opt/libpq/bin:$PATH"

# # Go
export GOPATH="$WK/go"
export PATH=$PATH:$GOPATH/bin

# # Javascript
# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"

export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
export PUPPETEER_EXECUTABLE_PATH=`which chromium`
