# Load necessary files
if [ -d $HOME/.zsh ]; then
  for file in $HOME/.zsh/*.zsh; do
    source $file
  done
fi

# Support 256-color terminals
export TERM=screen-256color

# export WK="$HOME/workspace"
#
# export PATH=$PATH:$WK/aaku/i3/scripts

# Ruby rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# Go
export GOPATH="$WK/go"
export PATH=$PATH:/usr/local/go/bin
